# Generated by Django 4.1.2 on 2023-12-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlavniLik',
            fields=[
                ('idGlavniLik', models.AutoField(primary_key=True, serialize=False)),
                ('nazivGlavniLik', models.CharField(max_length=30)),
                ('opisGlavniLik', models.CharField(max_length=500)),
            ],
        ),
    ]
