# Generated by Django 4.1.2 on 2023-12-27 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strip',
            fields=[
                ('idStrip', models.AutoField(primary_key=True, serialize=False)),
                ('godinaIzdanja', models.IntegerField()),
                ('broj', models.IntegerField()),
                ('nazivStrip', models.CharField(max_length=50)),
                ('idGlavniLik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.glavnilik')),
            ],
        ),
    ]
