# Generated by Django 4.1.2 on 2023-12-28 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_strip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kolekcija',
            fields=[
                ('idKolekcija', models.AutoField(primary_key=True, serialize=False)),
                ('datumDodavanja', models.DateField()),
                ('idKorisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idStrip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.strip')),
            ],
        ),
    ]
