# Generated by Django 4.1.2 on 2023-12-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_kolekcija'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kolekcija',
            name='datumDodavanja',
            field=models.DateField(auto_now_add=True),
        ),
    ]
