# Generated by Django 4.1.2 on 2023-12-29 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_alter_kolekcija_datumdodavanja'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaZelja',
            fields=[
                ('idListaZelja', models.AutoField(primary_key=True, serialize=False)),
                ('idKorisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idStrip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.strip')),
            ],
        ),
    ]
