# Generated by Django 4.1.2 on 2023-12-29 19:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_listazelja'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='listazelja',
            unique_together={('idStrip', 'idKorisnik')},
        ),
    ]
