# Generated by Django 4.1.2 on 2024-01-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_stanje_statusoglasa_oglas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oglas',
            name='datumObjave',
            field=models.DateField(auto_now_add=True),
        ),
    ]
