# Generated by Django 4.1.2 on 2024-01-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_oglas_datumobjave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oglas',
            name='idOglas',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
